config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'exchanges/index'
  get 'exchanges/show'
  get 'buy/bitcoin', to: 'buy_rate#bitcoin', as: :buy_bitcoin
  get 'sell/bitcoin', to: 'sell_rate#bitcoin', as: :sell_bitcoin

  # get 'buy/:coin', to: "buy_rate#buy", as: :buy_coin

  get 'learn', to: 'learning_portal#bitcoin', as: :learn

  get 'learn/bitcoin', to: 'learning_portal#bitcoin', as: :learn_bitcoin
  get 'learn/bitcoin/:id', to: 'learning_portal#show', as: :learn_bitcoin_show
  get 'learn/introduction-to-cryptocurrency', to: 'learning_portal#introduction', as: :learn_intro
  get 'learn/cryptocurrency-origin', to: 'learning_portal#origin', as: :learn_origin
  get 'learn/cryptocurrency-pros-cons', to: 'learning_portal#proscons', as: :learn_proscons
  get 'learn/cryptocurrency-types', to: 'learning_portal#types', as: :learn_type
  get 'learn/cryptocurrency-risks-dangers', to: 'learning_portal#risks-dangers', as: :learn_risk
  get 'learn/cryptocurrency-legalities', to: 'learning_portal#legalities', as: :learn_legalities
  get 'learn/cryptocurrency-wallets', to: 'learning_portal#wallets', as: :learn_wallets
  get 'learn/cryptocurrency-tips', to: 'learning_portal#tips', as: :learn_tips
  get 'learn/cryptocurrency-future', to: 'learning_portal#future', as: :learn_future


  root to: 'pages#home', as: :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create]
end

app/controllers/learning_portal_controller.rb
class LearningPortalController < ApplicationController
  # def show
  #   @learning = Learning.find(params[:id])
  # end


end

app/views/learning_portal/_content_footer.html.erb
      <div class="learn-buttons">
        <div class="col-lg-12">
          <%= link_to "Next: Introduction to cryptocurrency", learn_intro_path, class: "btn btn-link" %>
        </div>
      </div>
      <div class="row learn-buttons">
        <div class="col-lg-12">
          <%= link_to "Learning portal home", learn_bitcoin_path, class: "btn btn-sm btn-rounded btn-outline-primary mt-2" %>
        </div>
      </div><!-- /buttons -->
    </div><!-- /crypto-learn-wrapper -->
  </div><!-- /row-learning -->
</div><!-- -container  -->

app/views/learning_portal/_sidebar.html.erb
<div class="container learn-container-padding">
  <div class="row-learning">
    <div class="learn-sidebar col-lg-4 ">
      <div id="tab-0" class="tab-content current">
        <ul>
          <li>
            <a class="sidebar-item" href="/learn/introduction-to-cryptocurrency">
              <div class="number"><span></span></div>
              <div class="sidebar-holder">
                <div class="article-img">
                  <%= image_tag("bitcoin-logo.png") %>
                </div>
                <div class="sidebar-content">
                  <h5>Introduction to cryptocurrency</h5>
                </div>
              </div>
            </a>
          </li>

          <li>
            <a class="sidebar-item" href="/learn/cryptocurrency-origin">
              <div class="number"><span></span></div>
              <div class="sidebar-holder">
                <div class="article-img">
                  <%= image_tag("ethereum.png") %>
                </div>
                <div class="sidebar-content">
                  <h5>Origins of cryptocurrency</h5>
                </div>
              </div>
            </a>
          </li>

          <li>
            <a class="sidebar-item" href="/learn/cryptocurrency-pros-cons">
              <div class="number"><span></span></div>
              <div class="sidebar-holder">
                <div class="article-img">
                  <%= image_tag("ripple.png") %>
                </div>
                <div class="sidebar-content">
                  <h5>Cryptocurrency pros & cons</h5>
                </div>
              </div>
            </a>
          </li>

          <li>
            <a class="sidebar-item" href="/learn/cryptocurrency-types">
              <div class="number"><span></span></div>
              <div class="sidebar-holder">
                <div class="article-img">
                  <%= image_tag("litecoin.png") %>
                </div>
                <div class="sidebar-content">
                  <h5>Types of cryptocurrency</h5>
                </div>
              </div>
            </a>
          </li>

          <li>
            <a class="sidebar-item" href="/learn/cryptocurrency-risks-dangers">
              <div class="number"><span></span></div>
              <div class="sidebar-holder">
                <div class="article-img">
                  <%= image_tag("monero.png") %>
                </div>
                <div class="sidebar-content">
                  <h5>Risks and dangers of cryptocurrency</h5>
                </div>
              </div>
            </a>
          </li>

          <li>
            <a class="sidebar-item" href="/learn/cryptocurrency-legalities">
              <div class="number"><span></span></div>
              <div class="sidebar-holder">
                <div class="article-img">
                  <%= image_tag("legalities.png") %>
                </div>
                <div class="sidebar-content">
                  <h5>The legalities of cryptocurrency</h5>
                </div>
              </div>
            </a>
          </li>

          <li>
            <a class="sidebar-item" href="/learn/cryptocurrency-wallets">
              <div class="number"><span></span></div>
              <div class="sidebar-holder">
                <div class="article-img">
                  <%= image_tag("wallet.png") %>
                </div>
                <div class="sidebar-content">
                  <h5>Wallets of cryptocurrency</h5>
                </div>
              </div>
            </a>
          </li>

          <li>
            <a class="sidebar-item" href="/learn/cryptocurrency-tips">
              <div class="number"><span></span></div>
              <div class="sidebar-holder">
                <div class="article-img">
                  <%= image_tag("crypto-tips.png") %>
                </div>
                <div class="sidebar-content">
                  <h5>Cryptocurrency tips & tricks</h5>
                </div>
              </div>
            </a>
          </li>

          <li>
            <a class="sidebar-item" href="/learn/cryptocurrency-future">
              <div class="number"><span></span></div>
              <div class="sidebar-holder">
                <div class="article-img">
                  <%= image_tag("crypto-future.png") %>
                </div>
                <div class="sidebar-content">
                  <h5>Future of cryptocurrency</h5>
                </div>
              </div>
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="crypto-learn-wrapper col-xs-12 col-lg-8 col-lg-push-4">

app/views/learning_portal/bitcoin.html.erb
<div class="learn-detail">
  <div class="row-learning">

    <div class="learn-sidebar col-md-4 col-sm-12 col-xs-12">
      <div>

        <div id="tab-0" class="tab-content current">
          <ul>

            <li>
              <a class="sidebar-item" href="/learn/introduction-to-cryptocurrency">
                <div class="number"><span></span></div>
                <div class="sidebar-holder">
                  <div class="article-img">
                    <%= image_tag("bitcoin-logo.png") %>
                  </div>
                  <div class="sidebar-content">
                    <h5>Introduction to cryptocurrency</h5>
                  </div>
                </div>
              </a>
            </li>

            <li>
              <a class="sidebar-item" href="/learn/cryptocurrency-origin">
                <div class="number"><span></span></div>
                <div class="sidebar-holder">
                  <div class="article-img">
                    <%= image_tag("ethereum.png") %>
                  </div>
                  <div class="sidebar-content">
                    <h5>Origins of cryptocurrency</h5>
                  </div>
                </div>
              </a>
            </li>

            <li>
              <a class="sidebar-item" href="/learn/cryptocurrency-pros-cons">
                <div class="number"><span></span></div>
                <div class="sidebar-holder">
                  <div class="article-img">
                    <%= image_tag("ripple.png") %>
                  </div>
                  <div class="sidebar-content">
                    <h5>Cryptocurrency pros & cons</h5>
                  </div>
                </div>
              </a>
            </li>

            <li>
              <a class="sidebar-item" href="/learn/cryptocurrency-types">
                <div class="number"><span></span></div>
                <div class="sidebar-holder">
                  <div class="article-img">
                    <%= image_tag("litecoin.png") %>
                  </div>
                  <div class="sidebar-content">
                    <h5>Types of cryptocurrency</h5>
                  </div>
                </div>
              </a>
            </li>

            <li>
              <a class="sidebar-item" href="/learn/cryptocurrency-risks-dangers">
                <div class="number"><span></span></div>
                <div class="sidebar-holder">
                  <div class="article-img">
                    <%= image_tag("monero.png") %>
                  </div>
                  <div class="sidebar-content">
                    <h5>Risks and dangers of cryptocurrency</h5>
                  </div>
                </div>
              </a>
            </li>

            <li>
              <a class="sidebar-item" href="/learn/cryptocurrency-legalities">
                <div class="number"><span></span></div>
                <div class="sidebar-holder">
                  <div class="article-img">
                    <%= image_tag("legalities.png") %>
                  </div>
                  <div class="sidebar-content">
                    <h5>The legalities of cryptocurrency</h5>
                  </div>
                </div>
              </a>
            </li>

            <li>
              <a class="sidebar-item" href="/learn/cryptocurrency-wallets">
                <div class="number"><span></span></div>
                <div class="sidebar-holder">
                  <div class="article-img">
                    <%= image_tag("wallet.png") %>
                  </div>
                  <div class="sidebar-content">
                    <h5>Wallets of cryptocurrency</h5>
                  </div>
                </div>
              </a>
            </li>

            <li>
              <a class="sidebar-item" href="/learn/cryptocurrency-tips">
                <div class="number"><span></span></div>
                <div class="sidebar-holder">
                  <div class="article-img">
                    <%= image_tag("crypto-tips.png") %>
                  </div>
                  <div class="sidebar-content">
                    <h5>Cryptocurrency tips & tricks</h5>
                  </div>
                </div>
              </a>
            </li>

            <li>
              <a class="sidebar-item" href="/learn/cryptocurrency-future">
                <div class="number"><span></span></div>
                <div class="sidebar-holder">
                  <div class="article-img">
                    <%= image_tag("crypto-future.png") %>
                  </div>
                  <div class="sidebar-content">
                    <h5>Future of cryptocurrency</h5>
                  </div>
                </div>
              </a>
            </li>

          </ul>
        </div>
      </div>
    </div>

    <div class="crypto-learn-wrapper col-md-8 col-md-push-4">

      <h1>Welcome to the exciting world of cryptocurrency</h1>

      <div class="crypto-learn-content">
        <div style="text-align:center"><%= image_tag("crypto-welcome.png") %></div>
        <br>

        <p style="font-size: 25px line-height: px">
          It is hard to find people who have never heard of cryptocurrency before, thanks to its rapid growth. Cryptocurrency is only a term used to describe the different types of currencies inside the cryptocurrency market. The most common currency is <strong><em>Bitcoin</em></strong>, followed be other strong-performing currencies such as <strong><em>Ethereum</em></strong>, <strong><em>Litecoin</em></strong>, and many, many more
        </p>
        <br>
        <p>
          Here in our library, you will find all the tools you need to educate yourself in order to be a promising investor in the cryptocurrency market. The topics range from the history and the types of cryptocurrency to the risks and dangers of it.
        </p>
        <br>
        <p>
          Be sure to read everything carefully as the cryptocurrency market, while exciting, is rather volatile at the moment. You need to make sure you educate yourself enough before delving deeper.
        </p>
        <div class="learn-buttons">
          <%= link_to "Learning portal home", learn_bitcoin_path, class: "btn btn-info" %>
          <%= link_to "Next: Introduction to cryptocurrency", learn_intro_path, class: "btn btn-link" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/learning_portal/future.html.erb
<%= render 'sidebar' %>

      <h1>Future of cryptocurrency</h1>

      <%= image_tag("crypto-future-big.png") %>
      <br>
      <br>
      <br>

      <p style="font-size: 25px line-height: px">
        Research company Ipsos on behalf of ING Bank B.V. has conducted a study on how cryptocurrencies are perceived across Europe, Australia and the U.S., which reveals that interest in the technology is expected to double in the future.While only 9 percent of respondents own crypto, 25 percent said they will own some in the future. The highest percent (18 percent) of crypto ownership is reported in Turkey, while the lowest (4 percent) is in Luxembourg.
      </p>

      <p>
        According to the study, 66 percent of Europeans have heard of cryptocurrency, of which 77 percent are men and 55 percent are women; 35 percent agreed that crypto is the “future of spending online,” while 35 percent said it will increase in value in the following 12 months. The share of awareness of crypto is equal to or exceeds 50 percent in every surveyed country, with the highest rate in Austria (79 percent) and Poland (77 percent). In the U.S., 57 percent of respondents have heard of cryptocurrency.
      </p>

      <p>
        Earlier this month, consulting firm Capgemini found in its World Wealth Report 2018 that interest in cryptocurrencies has notably grown among high-net-worth individuals. According to the report, nearly one-third of surveyed individuals expressed high interest in cryptocurrencies. Interest in crypto was much higher among younger investors, with 70 percent of respondents under 40 attaching great importance to having their wealth managers provide information crypto, compared to only 13 percent of respondents 60 and over.
      </p>
<%= render 'content_footer' %>

app/views/learning_portal/home.html.erb
<section id="home-banner">
  <div class="banner">
    <h1 id="demo">We Make Cryptocurrency Easy</h1>
  </div>
</section>

<div class="col-lg-10 col-md-offset-1 card" id="learn-section">
  <h1>Learn about Bitcoin</h1>
  <p>Discover Bitcoin</p>

  <ul>
    <li><%= link_to 'learn about bitcoin', learn_bitcoin_path  %></li>
    <li><%= link_to 'buy bitcoin', buy_bitcoin_path  %></li>
    <li><%= link_to 'sell bitcoin', sell_bitcoin_path  %></li>
    <li><%= link_to 'home', home_path  %></li>
  </ul>


</div>

app/views/learning_portal/introduction.html.erb
<%= render 'sidebar' %>
      <h1>Introduction to cryptocurrency</h1>

          <%= image_tag("what-is-crypto.png") %>
          <br>
          <br>
        <iframe width="700" height="400" src="https://www.youtube.com/embed/pwaZYFPLAdI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen"></iframe>
        <br>
        <br>
        <p style="font-size: 55px line-height: px">
          Cryptocurrencies, like Bitcoin, aren't actual physical coins, but they've become a financial phenomenon in their own right. Here is your comprehensive guide for understanding cryptocurrency.
        </p>
        <br>
        <p>
          Wondering if it's the right time to break into the cryptocurrency market? That makes sense, especially since there never seems to be a clearly perfect moment.

          The journey cryptocurrency owners, especially ones who have been there since the beginning, have been incredibly rocky. Look at Bitcoin. It stagnated as an almost worthless investment before skyrocketing to a price of $20,000 in December of 2017. It has fallen off significantly since, but a statement was made. Cryptocurrencies were a joke just a few years ago; now, former President Bill Clinton is set to be keynote speaker at the Swell conference created by Ripple.
        </p>
        <br>
        <p>
          Cryptocurrencies, or virtual currencies, are digital means of exchange created and used by private individuals or groups. Because most cryptocurrencies aren’t regulated by national governments, they’re considered alternative currencies – mediums of financial exchange that exist outside the bounds of state monetary policy.
        </p>
        <br>
        <p>
          Cryptocurrencies use cryptographic protocols, or extremely complex code systems that encrypt sensitive data transfers, to secure their units of exchange. Cryptocurrency developers build these protocols on advanced mathematics and computer engineering principles that render them virtually impossible to break, and thus to duplicate or counterfeit the protected currencies. These protocols also mask the identities of cryptocurrency users, making transactions and fund flows difficult to attribute to specific individuals or groups.
        </p>
        <br>
        <br>
        <br>
 <%= render 'content_footer' %>

app/views/learning_portal/legalities.html.erb
<%= render 'sidebar' %>
      <h1>The legalities of cryptocurrency</h1>

      <%= image_tag("legalitiesbig.png") %>
      <br>
      <br>
      <br>

      <p style="font-size: 25px line-height: px">
        The legal status of cryptocurrencies varies substantially from country to country and is still undefined or changing in many of them. While some countries have explicitly allowed their use and trade, others have banned or restricted it. According to the Library of Congress, an "absolute ban" on trading or using cryptocurrencies applies in eight countries: Algeria, Bolivia, Egypt, Iraq, Morocco, Nepal, Pakistan, and the United Arab Emirates. An "implicit ban" applies in another 15 countries, which include Bahrain, Bangladesh, China, Colombia, the Dominican Republic, Indonesia, Iran, Kuwait, Lesotho, Lithuania, Macau, Oman, Qatar, Saudi Arabia and Taiwan. In the United States and Canada, state and provincial securities regulators, coordinated through the North American Securities Administrators Association, are investigating "bitcoin scams" and ICOs in 40 jurisdictions.
      </p>
      <br>
      <p>
        Cryptocurrencies are a potential tool to evade economic sanctions for example against Russia, Iran, or Venezuela. In April 2018, Russian and Iranian economic representatives met to discuss how to bypass the global SWIFT system through decentralized blockchain technology. Russia also secretly supported Venezuela with the creation of the petro (El Petro), a national cryptocurrency initiated by the Maduro government to obtain valuable oil revenues by circumventing US sanctions.
      </p>

      <br>
      <iframe width="700" height="400" src="https://www.youtube.com/embed/lX82gLHkRrE" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen"></iframe>
      <br>
      <br>
      <br>
<%= render 'content_footer' %>

app/views/learning_portal/origin.html.erb
<%= render 'sidebar' %>

<h1>Origins of cryptocurrency</h1>

<%= image_tag("crypto-history.png") %>
<br>
<br>
<iframe width="700" height="400" src="https://www.youtube.com/embed/GKFDujESgjA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen"></iframe>
<br>
<br>
<p style="font-size: 25px line-height: px">
  Cryptocurrency’s technical foundations date back to the early 1980s, when an American cryptographer named David Chaum invented a “blinding” algorithm that remains central to modern web-based encryption. The algorithm allowed for secure, unalterable information exchanges between parties, laying the groundwork for future electronic currency transfers. This was known as “blinded money.”
</p>
<br>
<p>
  By the late 1980s, Chaum enlisted a handful of other cryptocurrency enthusiasts in an attempt to commercialize the concept of blinded money. After relocating to the Netherlands, he founded DigiCash, a for-profit company that produced units of currency based on the blinding algorithm. Unlike Bitcoin and most other modern cryptocurrenncies, DigiCash’s control wasn’t decentralized. Chaum’s company had a monopoly on supply control, similar to central banks’ monopoly on fiat currencies
</p>
<br>
<p>
  Around the same time, an accomplished software engineer named Wei Dai published a white paper on b-money, a virtual currency architecture that included many of the basic components of modern cryptocurrencies, such as complex anonymity protections and decentralization. However, b-money was never deployed as a means of exchange.
</p>
<br>
<p>
  Shortly thereafter, a Chaum associate named Nick Szabo developed and released a cryptocurrency called Bit Gold, which was notable for using the blockchain system that underpins most modern cryptocurrencies. Like DigiCash, Bit Gold never gained popular traction and is no longer used as a means of exchange.
</p>

<%= render 'content_footer' %>

app/views/learning_portal/proscons.html.erb
<%= render 'sidebar' %>

<h1>Cryptocurrency pros & cons</h1>

<%= image_tag("crypto-pros-cons.png") %>
<br>
<br>
<br>

<p style="font-size: 25px line-height: px">
  Lots of advocates of Cryptocurrency will tell you that it is the best financial system ever invented and that it has no faults. On the other hand, some people will point to examples such as the illegal deep-web market Silk Road to try and convince you that it is just a tool for crime. Techies love it – the DEA hates it – lawmakers are confused by it… but you’ll need to form your own opinion. Below you’ll find an evolving list of Cryptocurrency pros and cons to help you understand what all the fuss is about.
</p>

<br>
<iframe width="700" height="400" src="https://www.youtube.com/embed/ykSdvGxGEjc" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen"></iframe>
<br>
<br>

<div class="row">

  <div class="col-lg-6">
    <h2 style="text-align: center">Pros</h2>
    <ul>
      <li>Cryptocurrency is legal and, if it is claimed correctly for tax purposes, opens up another avenue for transactions.</li>
      <br>
      <li>Most cryptocurrencies are built from the bottom up with security and privacy in mind. This means users can expect transactions to be private and secure.</li>
      <br>
      <li>Since the cryptocurrency market is volatile it can be a high reward (albeit high risk) investment.</li>
      <br>
      <li>Transactions are quick, permanent, and hard to fake, this eliminates a lot of the fraud issues banks deal with.</li>
      <br>
      <li>Cryptocurrency makes trading anywhere in the world easy. It’s a decentralized currency.</li>
      <br>
    </ul>
  </div>
  <div class="col-lg-6">
    <h2 style="text-align: center">Cons</h2>
    <ul>
      <li>Cryptocurrency is only accepted by certain vendors. Between that and fluctuating prices the money saved in transaction costs could be negligible.</li>
      <br>
      <li>There is no way to recover coins if they are lost and there is no system in place to protect the value of your coin</li>
      <br>
      <li>Any given cryptocurrency lacks the flexibility of centralized currency due to it’s non-inflationary nature.</li>
      <br>
      <li>The cryptocurrency market is volatile. In 2014 the value of bitcoin ranged between about $30 and $1000!</li>
      <br>
      <li>The coin you trade for a legal thing today can be used to fund awfully illegal things tomorrow. The notorious Silk Road allowed for illegal blackmarket transactions</li>
    </ul>
  </div>
</div>

<%= render 'content_footer' %>

app/views/learning_portal/risks-dangers.html.erb
<%= render 'sidebar' %>

<h1>The dangers of cryptocurrency</h1>

<%= image_tag("crypto-risks.png") %>
<br>
<br>
<iframe width="700" height="400" src="https://www.youtube.com/embed/tXBwcedQuQ0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen"></iframe>
<br>
<br>

<p style="font-size: 25px line-height: px">
  It is good to be realistic and remember that cryptocurrency is not all butterflies. Here we explore in-depth about the risks and dangers of the industry, and how you can avoid them.
</p>
<br>
<p>
  There are plenty of opportunities to make lots of money in the crypto market, and you should be patient and wise to acquire the right knowledge before investing. Don’t be the person that invests based on the current hype. Do your research first. If it’s too complex, look for answers. The cryptocurrency community is filled with awesome individuals that can simplify things and help you along the way. If you need someone to invest for you, make sure you ask questions to verify their credibility. There’s no such thing as earning fixed returns when investing in cryptos. Don’t fall for the various scams or Ponzi schemes which are of late, becoming more prevalent in the market.
</p>
<br>
<p>
  One of the most fundamental skills that you absolutely must possess is the ability to identify cryptocurrencies that are backed by solid fundamentals. There are hundreds of coins available, and there is a tendency for most to overlook the fundamentals of the coin and make investment decisions based on hype. This is especially common since many don’t understand the mechanics of the coins they invest in. They tend to just follow the hyped crowd.
</p>
<br>
<p>
  Venturing into a new and revolutionary technology can be daunting but exciting at the same time. We hope that you make lots of money investing in cryptocurrencies, whilst being aware of the real risks and dangers. We will continually create more content and resources to help you in your journey. Have fun and stay safe!
</p>
<br>

<%= render 'content_footer' %>

app/views/learning_portal/tips.html.erb
<%= render "sidebar" %>

      <h1>Cryptocurrency tips & tricks</h1>

      <%= image_tag("crypto-tips-big.png") %>
      <br>
      <br>
      <br>

      <p style="font-size: 25px line-height: px">
        A common beginners’ mistake is to look at the coin’s price rather than the market cap. Just as you asses a company by its market cap performance, which is calculated by multiplying the number of shares times a single share’s price, the same is done for Altcoins. The number of existing coins in circulation times the coin’s price. For a low price coin, such as Ripple, there is solely a psychological influence on the buyers. There is no difference whether one Ripple equals one dollar, and there are a billion Ripples out, or if one Ripple equals a thousand dollars and there are million units of Ripple.
      </p>


      <p>
        Crypto is really unpredictable. While reaping profits of hundreds of percent, the section withstands now and will continue getting dozens of billions of dollars erased flat out in the future. When Bitcoin loses its value against the US dollar Altcoins usually go through the same process. Simple math shows that even holding a part of the portfolio in Altcoins, such as Ethereum and Litecoin, is usually not enough to avoid getting a big chunk of the portfolio’s USD worth wiped out following a Bitcoin dump.
      </p>


      <p>
        Good traders acknowledge their mistakes, and more importantly – analyze and learn from them, thus improving their skills for understanding the market. So which kind of trader are you? Did you find yourself somewhere in the article? We would love to hear on the comments section below, and you are welcome to share this article with whoever you see as relevant.
      </p>
<%= render 'content_footer' %>

app/views/learning_portal/wallets.html.erb
<%= render 'sidebar' %>

      <h1>Wallets of cryptocurrency</h1>

      <%= image_tag("walletbig.png") %>
      <br>
      <br>
      <br>

      <p style="font-size: 25px line-height: px">
        A cryptocurrency wallet stores the public and private keys which can be used to receive or spend the cryptocurrency. A wallet can contain multiple public and private key pairs. As of January 2018, there are over thirteen hundred cryptocurrencies; the first and best known is bitcoin. The cryptocurrency itself is not in the wallet. In case of bitcoin and cryptocurrencies derived from it, the cryptocurrency is decentrally stored and maintained in a publicly available ledger. Every piece of cryptocurrency has a private key. With the private key, it is possible to write in the public ledger, effectively spending the associated cryptocurrency.
      </p>

      <br>
      <iframe width="700" height="400" src="https://www.youtube.com/embed/NI0OsEL92_0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen"></iframe>
      <br>
      <br>
      <h5>Wallet characteristics</h5>
      <ul>
        <li>Multicurrency</li>
        <li>Software wallet</li>
        <li>Hardware wallet</li>
        <li>Watch-only wallet</li>
        <li>Multisignature wallet</li>
      </ul>
      <br>
      <br>
      <p>
        When choosing a wallet, the owner must keep in mind who is supposed to have access to (a copy of) the private keys and thus potentially has access to the cryptocurrency. Just like with a bank, the user needs to trust the provider to keep the cryptocurrency safe. Trust was misplaced in the case of the Mt. Gox exchange, which 'lost' most of their clients' bitcoins. Downloading a cryptocurrency wallet from a wallet provider to a computer or phone does not automatically mean that the owner is the only one who has a copy of the private keys. For example with Coinbase, it is possible to install a wallet on a phone and to also have access to the same wallet through their website. A wallet can also have known or unknown vulnerabilities. For receiving cryptocurrency, access to the receiving wallet is not needed. The sending party only needs to know the destination address. Anyone can send cryptocurrency to an address. Only the one who has the private key of the corresponding address can use it.
      </p>
<%= render 'content_footer' %>