config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'exchanges/index'
  get 'exchanges/show'
  get 'buy/bitcoin', to: 'buy_rate#bitcoin', as: :buy_bitcoin
  get 'sell/bitcoin', to: 'sell_rate#bitcoin', as: :sell_bitcoin

  # get 'buy/:coin', to: "buy_rate#buy", as: :buy_coin

  get 'learn', to: 'learning_portal#bitcoin', as: :learn

  get 'learn/bitcoin', to: 'learning_portal#bitcoin', as: :learn_bitcoin
  get 'learn/bitcoin/:id', to: 'learning_portal#show', as: :learn_bitcoin_show
  get 'learn/introduction-to-cryptocurrency', to: 'learning_portal#introduction', as: :learn_intro
  get 'learn/cryptocurrency-origin', to: 'learning_portal#origin', as: :learn_origin
  get 'learn/cryptocurrency-pros-cons', to: 'learning_portal#proscons', as: :learn_proscons
  get 'learn/cryptocurrency-types', to: 'learning_portal#types', as: :learn_type
  get 'learn/cryptocurrency-risks-dangers', to: 'learning_portal#risks-dangers', as: :learn_risk
  get 'learn/cryptocurrency-legalities', to: 'learning_portal#legalities', as: :learn_legalities
  get 'learn/cryptocurrency-wallets', to: 'learning_portal#wallets', as: :learn_wallets
  get 'learn/cryptocurrency-tips', to: 'learning_portal#tips', as: :learn_tips
  get 'learn/cryptocurrency-future', to: 'learning_portal#future', as: :learn_future


  root to: 'pages#home', as: :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create]
end

app/views/shared/_footer.html.erb
<!-- footer -->
<footer class="bg-dark text-white">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 text-center">
        <h2>Subscribe to receive rate alerts.</h2>
        <form class="form form-cta mt-3">
          <div class="form-group">
            <div class="row gutter-1">
              <div class="col-8">
                <input type="email" class="form-control form-control-rounded px-4" id="exampleInputEmail1" placeholder="Insert your email">
              </div>
              <div class="col-4">
                <button type="submit" class="btn btn-white btn-rounded btn-block">Subscribe</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="separator-top">
    <div class="container py-5">
      <div class="row justify-content-between align-items-center">
        <div class="col-md-5 text-center text-md-left">
          <ul class="nav">
            <li class="nav-item">
              <%= link_to 'Compare', buy_bitcoin_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Learning Portal', learn_path, class:"nav-link" %>
            </li>
          </ul>
        </div>
        <div class="col-md-2 text-center">
          <%= image_tag "logo.png", class:"logo-sm" %>
          <!-- <img class="logo-sm" src="../../assets/images/demo/logo/logo-light.svg" alt="Logo"> -->
        </div>
        <div class="col-md-5 text-center text-md-right">
          <ul class="socials">
            <li><a href="" class="fab fa-instagram"></a></li>
            <li><a href="" class="fab fa-twitter"></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- / footer -->

app/views/shared/_navbar.html.erb
<!-- header -->
<header class="header-sticky header-light">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand" href="<%= home_path %>">
        <%= image_tag "logo.png", class: "navbar-logo navbar-logo-dark" %>
        <!-- <img class="navbar-logo navbar-logo-light" src="../../assets/images/demo/logo/logo-light.svg" alt="Logo"> -->
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="burger"><span></span></span></button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav align-items-center mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Compare
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <!-- <a class="dropdown-item" href="../../landing-pages.html"> -->
                <div class="dropdown-item">
                  <span><%= link_to 'Bitcoin Prices', buy_bitcoin_path %></span>
                </div>
                <!-- <p>Something here</p> -->
              </a>
<!--               <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="../../inner-pages.html">
                <span>Ethereum Prices</span> -->
                <!-- <p>Something here</p> -->
<!--               </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="../../app-pages.html">
                <span>Litecoin Prices</span> -->
                <!-- <p>Something here</p> -->
              <!-- </a> -->
            </div>
          </li>
          <li class="nav-item dropdown dropdown-mega">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown-1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Learning Portal
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown-1">
              <div class="row">
                <div class="col">
                  <ul class="mega-list">
                    <!-- <li>link_to 'Get Started', learn_path, class:'highlight'</li> -->
                    <h4>Bitcoin 101</h4>
                    <li><%= link_to 'What is Bitcoin?', learn_intro_path %></li>
                    <li><%= link_to 'Where did Bitcoin come from?', learn_origin_path %></li>
                    <li><%= link_to 'How do I get Bitcoin?', learn_wallets_path %></li>
                    <li><%= link_to 'Is Bitcoin safe?', learn_risk_path %></li>
                  </ul>
                </div>
                <div class="col">
                  <ul class="mega-list">
                    <h4>Guides</h4>
                    <li><%= link_to 'What is Bitcoin?', learn_path %></li>
                    <li><%= link_to 'Where did Bitcoin come from?', learn_path %></li>
                    <li><%= link_to 'How do I get Bitcoin?', learn_path %></li>
                    <li><%= link_to 'Is Bitcoin safe?', learn_path %></li>
                  </ul>
                </div>
                <div class="col">
                  <ul class="mega-list">
                    <h4>Glossary</h4>
                    <li><%= link_to 'What is Bitcoin?', learn_path %></li>
                    <li><%= link_to 'Where did Bitcoin come from?', learn_path %></li>
                    <li><%= link_to 'How do I get Bitcoin?', learn_path %></li>
                    <li><%= link_to 'Is Bitcoin safe?', learn_path %></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
        </ul>

<!--         <ul class="navbar-nav align-items-center mr-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown-2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Michael Doe
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="">Profile</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="">Sign In</a>
              <a class="dropdown-item" href="">Sign Out</a>
            </div>
          </li>
        </ul> -->
      </div>
    </nav>
  </div>
</header>
<!-- header -->

app/views/shared/_searchbar.html.erb
<div class="searchbar-main">
  <ul class="nav nav-tabs switch-toggle switch-ios">
    <li class="active"><a data-toggle="tab" href="#buy_price">BUY BITCOIN</a></li>
    <li><a data-toggle="tab" href="#sell_price">SELL BITCOIN</a></li>
  </ul>

  <div class="tab-content">
    <div id="buy_price" class="tab-pane fade in active">
      <div id="searchbar">
        <%= form_tag buy_bitcoin_path, method: :get do %>
          <%= text_field_tag :amount, params[:amount], class: "form-control", placeholder: "Enter USD amount"%>
            <button type="submit" class="btn btn-default btn-search--submit">
              <i class="fas fa-search"></i>
              Compare
            </button>
            <ul>
              <!-- PAYMENT METHODS FILTER SELECTION -->
              <li>
                <%= check_box_tag 'payment_methods[]', 'SWIFT Bank Transfer', true  %>
                <p>SWIFT Bank Transfer</p>
              </li>
              <li>
                <%= check_box_tag 'payment_methods[]', 'SEPA Bank Transfer', true  %>
                <p>SEPA Bank Transfer</p>
              </li>
              <li>
                <%= check_box_tag 'payment_methods[]', 'VISA', true  %>
                <p>VISA</p>
              </li>
              <li>
                <%= check_box_tag 'payment_methods[]', 'Mastercard', true  %>
                <p>Mastercard</p>
              </li>
              <li>
                <%= check_box_tag 'payment_methods[]', 'Paypal', true  %>
                <p>Paypal</p>
              </li>
              <li>
                <%= check_box_tag 'payment_methods[]', 'Sofort', true  %>
                <p>Sofort</p>
              </li>
              <li>
                <%= check_box_tag 'payment_methods[]', 'Giropay', true  %>
                <p>Giropay</p>
              </li>
              <li>
                <%= check_box_tag 'payment_methods[]', 'Skrill', true  %>
                <p>Skrill</p>
              </li>
              <li>
                <%= check_box_tag 'payment_methods[]', 'iDeal', true  %>
                <p>iDeal</p>
              </li>
              <li>
                <%= check_box_tag 'payment_methods[]', 'Bancontact / Mister', true  %>
                <p>Bancontact / Mister</p>
              </li>

              <!-- FEATURES FILTER SELECTION -->
              <li>
                <%= check_box_tag 'features[]', 'Beginner Friendly', false  %>
                <p>Beginner Friendly</p>
              </li>
              <li>
                <%= check_box_tag 'features[]', 'Instant Verification', false  %>
                <p>Instant Verification</p>
              </li>
              <li>
                <%= check_box_tag 'features[]', 'Integrated Wallet', false  %>
                <p>Integrated Wallet</p>
              </li>
            </ul>
        <% end %>
      </div>
    </div>

      <div id="sell_price" class="tab-pane fade">
        <div id="searchbar">
          <%= form_tag sell_bitcoin_path, method: :get do %>
            <%= text_field_tag :amount, params[:amount], class: "form-control", placeholder: "Enter bitcoin amount"%>
              <button type="submit" class="btn btn-default btn-search--submit">
                <i class="fas fa-search"></i>
                Compare
              </button>
          <% end %>
        </div>
      </div>
  </div>
</div>